### ISSUE TITLE
Discrepancies found in degree plans extracted into curriculums

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#7]
There are lots of differences. Currently evaluating why. My best guess is the difference in whether or not a class overlaps with a major course (in which case, that's fine)

**Comment by ArturoAmaya** [comment]
Currently investigating

**Comment by SheepTester** [comment]
One reason might be that curricula don't have terms, while degree plans do. I thought that curricula did have quarter-by-quarter plans, so it currently keeps the quarters they're in. I'm not sure if you've accounted for that, but I'll probably change `curriculum` to return a flattened list of courses instead of splitting them by the quarters they were in since the specific quarters probably depend on the college you're in

**Comment by ArturoAmaya** [comment]
Funnily enough, most of the ones I've seen don't, but that's a pretty great edit.
